<h1>Update</h1>
<?php
// module/Album/view/album/album/edit.phtml:

$title = 'Edit admin';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<?php
$form = $this->form;

$form->prepare();
$form->setAttribute('action', $this->url('admin/default', array('controller' => 'admin', 'action' => 'edit', 'id' =>$this->id)));
$form->setAttribute('method', 'post');

echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id'));
echo $this->formRow($form->get('title'));
echo $this->formRow($form->get('artist'));
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();